name: nllb-llm2vec # or your name
channels:
  # pytorch and nvidia need to superseed
  # conda-forge for cuda pytorch
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.4.1
  - pytorch-cuda=12.4
  - cuda
  - transformers
  - lightning=2.4
  - hydra-core
  - hydra-colorlog
  # for deepspeed
  - gcc
  - cxx-compiler

  # development dependencies
  - ipython
  - pytest
  - debugpy
  - pudb
  - pyright
  - pip
  - ruff

  - pip:
    - wandb
    - peft==0.13.0
    - bitsandbytes==0.44.0
    - deepspeed==0.15.1
    - seqeval
    - ruff-lsp
    # path to trident
    - -e ./.deps/trident/
